import { Icon, Table, TableModelProps } from 'doif-react-kit';
import React, { useMemo } from 'react';

function ResourcePage() {
  const model: TableModelProps[] = useMemo(
    () => [
      {
        label: '메뉴명',
        name: 'name',
        width: 250,
        align: 'left',
      },
      {
        label: '메뉴 코드',
        name: 'code',
        width: 250,
        align: 'left',
      },
      {
        label: '설명',
        name: 'description',
        width: 350,
        align: 'left',
      },
      {
        label: '사용 가능 상태',
        name: 'statusName',
        width: 120,
      },
      {
        label: 'URL',
        name: 'url',
        width: 250,
        align: 'left',
      },
      {
        label: '아이콘',
        name: 'icon',
        width: 120,
        formatter: (cellValue: any) => {
          return cellValue.props.value ? (
            <Icon icon={cellValue.props.value} />
          ) : (
            cellValue
          );
        },
      },
      {
        label: '구분',
        name: 'typeName',
        width: 120,
      },
      {
        label: '정렬 순서',
        name: 'sort',
        width: 100,
      },
      {
        label: '',
        name: 'resourceId',
        hidden: true,
      },
    ],
    [],
  );

  const data = useMemo(
    () => [
      {
        resourceId: 60,
        name: '개발자',
        description: '개발자 메뉴 카테고리',
        status: 'ENABLE',
        statusName: '가능',
        code: 'CATEGORY_DEV',
        parentId: null,
        paddingName: ' 개발자',
        sort: 99,
        depth: 1,
        path: '99',
        type: 'CATEGORY',
        typeName: '카테고리',
        icon: 'heart',
        url: null,
        childrenItems: [],
        subRows: [
          {
            resourceId: 61,
            name: '메뉴 관리',
            description: '메뉴 리소스 관리 메뉴',
            status: 'ENABLE',
            statusName: '가능',
            code: 'MENU_DEV_RESOURCE_MENU',
            parentId: 60,
            paddingName: '  메뉴 관리',
            sort: 1,
            depth: 2,
            path: '99-1',
            type: 'MENU',
            typeName: '메뉴',
            icon: 'lock',
            url: '/dev/menu',
            childrenItems: [],
            subRows: [],
          },
          {
            resourceId: 62,
            name: '페이지 관리',
            description: '페이지 리소스 관리 메뉴',
            status: 'ENABLE',
            statusName: '가능',
            code: 'MENU_DEV_RESOURCE_PAGE',
            parentId: 60,
            paddingName: '  페이지 관리',
            sort: 2,
            depth: 2,
            path: '99-2',
            type: 'MENU',
            typeName: '메뉴',
            icon: null,
            url: '/dev/page',
            childrenItems: [],
            subRows: [],
          },
          {
            resourceId: 63,
            name: '탭 관리',
            description: '탭 리소스 관리 메뉴',
            status: 'ENABLE',
            statusName: '가능',
            code: 'MENU_DEV_RESOURCE_TAB',
            parentId: 60,
            paddingName: '  탭 관리',
            sort: 3,
            depth: 2,
            path: '99-3',
            type: 'MENU',
            typeName: '메뉴',
            icon: null,
            url: '/dev/tab',
            childrenItems: [],
            subRows: [],
          },
          {
            resourceId: 64,
            name: '버튼 관리',
            description: '버튼 리소스 관리 메뉴',
            status: 'ENABLE',
            statusName: '가능',
            code: 'MENU_DEV_RESOURCE_BUTTON',
            parentId: 60,
            paddingName: '  버튼 관리',
            sort: 4,
            depth: 2,
            path: '99-4',
            type: 'MENU',
            typeName: '메뉴',
            icon: null,
            url: '/dev/button',
            childrenItems: [],
            subRows: [],
          },
          {
            resourceId: 65,
            name: '라벨 관리',
            description: '라벨 리소스 관리 메뉴',
            status: 'ENABLE',
            statusName: '가능',
            code: 'MENU_DEV_RESOURCE_LABEL',
            parentId: 60,
            paddingName: '  라벨 관리',
            sort: 5,
            depth: 2,
            path: '99-5',
            type: 'MENU',
            typeName: '메뉴',
            icon: null,
            url: '/dev/label',
            childrenItems: [],
            subRows: [],
          },
          {
            resourceId: 69,
            name: '테스트',
            description: '테스트 카테고리',
            status: 'ENABLE',
            statusName: '가능',
            code: 'CATEGORY_TEST',
            parentId: 60,
            paddingName: '  테스트',
            sort: 55,
            depth: 2,
            path: '99-55',
            type: 'CATEGORY',
            typeName: '카테고리',
            icon: 'heart',
            url: null,
            childrenItems: [],
            subRows: [
              {
                resourceId: 70,
                name: '테스트2',
                description: '테스트 카테고리2',
                status: 'ENABLE',
                statusName: '가능',
                code: 'CATEGORY_TEST2',
                parentId: 69,
                paddingName: '   테스트2',
                sort: 123,
                depth: 3,
                path: '99-55-123',
                type: 'CATEGORY',
                typeName: '카테고리',
                icon: 'pencil',
                url: null,
                childrenItems: [],
                subRows: [],
              },
            ],
          },
          {
            resourceId: 66,
            name: '메세지 관리',
            description: '메세지 리소스 관리 메뉴',
            status: 'ENABLE',
            statusName: '가능',
            code: 'MENU_DEV_RESOURCE_MESSAGE',
            parentId: 60,
            paddingName: '  메세지 관리',
            sort: 6,
            depth: 2,
            path: '99-6',
            type: 'MENU',
            typeName: '메뉴',
            icon: null,
            url: '/dev/message',
            childrenItems: [],
            subRows: [],
          },
        ],
      },
    ],
    [],
  );

  return (
    <Table caption="Row 선택 시" model={model} data={data} enableTreeTable />
  );
}

export default ResourcePage;
